### ISSUE TITLE
FDboost does not deal correctly with `is.bdfamily` families.

### ISSUE THREAD

**Issue by fabian-s** [boost-R/FDboost#1]
These now expect matrix valued responses `cbind(#success, #failures)` (gamboostLSS>1.5), but FDboost treats matrix valued responses as functions and shit's all fucked up. 

Code examples in supplement to Statmod discussion paper, too long & secret to post here.

**Comment by fabian-s** [comment]
Still not working with https://github.com/boost-R/mboost/commit/0326a2aaa1f84227d07673a59a85df97b3fa12db --
```r
set.seed(12) 
n <- 100
grid <- seq(0, 1, l = 20)
xfun <- t(replicate(n, dbeta(grid, runif(1, 3, 10), runif(1, 2, 7))))
xscalar <- rnorm(100)
y_success <- rbinom(n, size = 30, p = plogis(xscalar))
data <- list(y = cbind(y_success, y_fail = 30 - y_success), xfun = xfun, xscalar = xscalar)
m <- FDboost(y  ~ bbs(xscalar) + bsignal(xfun),
  timeformula = NULL, family=Binomial(type="glm"),
  data = data, control = boost_control(mstop = 50, nu = 0.05))
```
yields:
```
Error in FDboost(y ~ bbs(xscalar) + bsignal(xfun), timeformula = NULL,  : 
  The length of the response and number of observations of xfun do not match.
```
because the response matrix for the scalar responses is converted to a long vector in 
`response <- matrix(response, ncol = 1)` https://github.com/boost-R/FDboost/blob/master/R/FDboost.R#L566

**Comment by sbrockhaus** [comment]
Thanks for the bug report and the MWE. Works now :-)
