### ISSUE TITLE
options("mboost_indexmin") and bhistx() gives errors in coef()

### ISSUE THREAD

**Issue by sbrockhaus** [boost-R/FDboost#10]
If internally an index is used for model fitting for a model containing `bhistx()` some methods, e.g., `coef()`, no longer work: 

```
library(FDboost)

options("mboost_indexmin")

require(refund))
## simulate some data from a historical model
## the interaction effect is in this case not necessary
n <- 100
nygrid <- 35
data1 <- pffrSim(scenario = c("int", "ff"), limits = function(s,t){ s <= t }, 
                 n = n, nygrid = nygrid)
data1$X1 <- scale(data1$X1, scale = FALSE) ## center functional covariate                  
dataList <- as.list(data1)
dataList$tvals <- attr(data1, "yindex")

## create the hmatrix-object
X1h <- with(dataList, hmatrix(time = rep(tvals, each = n), id = rep(1:n, nygrid), 
                              x = X1, argvals = attr(data1, "xindex"), 
                              timeLab = "tvals", idLab = "wideIndex", 
                              xLab = "myX", argvalsLab = "svals"))
dataList$X1h <- I(X1h)   
dataList$svals <- attr(data1, "xindex")


#################################

options("mboost_indexmin" = 10000)

## do the model fit with main effect of bhistx() and interaction of bhistx() and bolsc()
mod <- FDboost(Y ~ bhistx(x = X1h, df = 5, knots = 5), 
               timeformula = ~ bbs(tvals, knots = 10), data = dataList)

coef_mod <- coef(mod)


###################################

options("mboost_indexmin" = 10)

## do the model fit with main effect of bhistx() and interaction of bhistx() and bolsc()
mod2 <- FDboost(Y ~ bhistx(x = X1h, df = 5, knots = 5), 
               timeformula = ~ bbs(tvals, knots = 10), data = dataList)

### breaks within predict
coef_mod2 <- coef(mod2)

```

**Comment by davidruegamer** [comment]
I still haven't figured out, where the rub is, but maybe we could just set `options("mboost_indexmin" = 10000)` in `coef` ? Because this does not throw an error:

```
options("mboost_indexmin" = 10000)

coef_mod2 <- coef(mod2)
```

even if `mod2` was fitted using `options("mboost_indexmin" = 10)` :upside_down_face:

**Comment by davidruegamer** [comment]
PS: The error is due to the fact, that `get_index` does not work with `hmatrix` objects. In details, if we use the mentioned option, we try to apply `get_index` to an object like this:

```
'data.frame':	1600 obs. of  4 variables:
 $ X1h    : AsIs [1:1600, 1:2] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  ..- attr(*, "x")= num [1:40, 1:40] 39 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "argvals")= num  0 0.0256 0.0513 0.0769 0.1026 ...
  ..- attr(*, "timeLab")= chr "t"
  ..- attr(*, "idLab")= chr "wideIndex"
  ..- attr(*, "xLab")= chr "x"
  ..- attr(*, "argvalsLab")= chr "s"
  ..- attr(*, "class")= chr  "AsIs" "hmatrix" "matrix"
 $ tvals  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ONEx   : num  1 1 1 1 1 1 1 1 1 1 ...
 $ ONEtime: num  1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "varnms")= chr  "svals" "tvals"
 - attr(*, "xm")= num  0 0.0256 0.0513 0.0769 0.1026 ...
 - attr(*, "ym")= num  0 0.0256 0.0513 0.0769 0.1026 ...
 - attr(*, "myargsHist")=List of 23
```

But you said something like that it isn't a problem for `bhist` (without `x`) baselearners? That would be odd.

**Comment by davidruegamer** [comment]
Since the error is caused by `bl[[w]]$predict(ens[ix], newdata = newdata, aggregate = agg)` in `bl_lin`, I think we do not have a choice, but to either redefine `indexmin` or throw an error and recommend to set `indexmin` to a larger value. All other options involve a complete restructuring of or `hmatrix` concept. A generic `get_index` function for `hmatrix`objects, for example, won't work, as the objectm, which we pass to `get_index` is an ordinary `data.frame`.

**Comment by sbrockhaus** [comment]
For models with response in long format, `"FDboostLong"`, even more methods break. `bhist()` is no problem as long as the model has a response matrix and not a response in long format. 
As the option is not helpful for functional covariates (it uses ties in the data to speed up computations and ties seem very unlikely in case of functional covariates), we decided to set the option to `+Inf` within `FDboost`.

**Comment by sbrockhaus** [comment]
https://github.com/boost-R/FDboost/commit/ea31b33ed5238cc6146778a43d58046d1533e926
