### ISSUE TITLE
Remaining errors in test file

### ISSUE THREAD

**Issue by davidruegamer** [boost-R/FDboost#9]
- [x] `plot` throws an error for model `m1`: `length(x) == length(y) & length(y) == length(id) is not TRUE`

- [x] `plot.bootstrapCI` fails for `m4`, `m4i`, `m4iii`, `m4iv`, `ms1a`, `ms2`. For the historical models, this happens as the function can't deal with interaction effects, which are stored as lists of matrices. For the scalar models, this is due to the fact, that the line `temp$value <- split(temp_CI, seq(nrow(temp_CI)))` in `plot.bootstrapCI` can't deal with scalar intercepts. 

- [x] `predict` and potentially many following methods throw an error for `m4ii` (most likely reason: the use of `myBlg`

- [x] `plotResiduals`, `validateFDboost` and `applyFolds` for factor response ('not implemented yet', see also #7 )

- [x] `coef(object[0])` fails for `m4iv`

**Comment by sbrockhaus** [comment]
Thanks a lot! I will try to fix most of this :-)

**Comment by sbrockhaus** [comment]
- [ ] for some models `predict(object[0])` does not work
- [ ] m4ii: `applyFolds can not deal with the following base-learner(s) without brackets: myBlg`

**Comment by sbrockhaus** [comment]
Regarding `plotResiduals()` and factor response: what is the desired behaviour?

**Comment by davidruegamer** [comment]
Boxplots per level? Or just use the generic plot function on `model$residuals`? Imo this is rather something the user should think about, isn't it?

**Comment by sbrockhaus** [comment]
Well, it is not that easy to solve it that way as `object$baselearner$get_data()` 
- is possibly blown up by `index` when the base-learner contains  `%X%` (for `%O%` `index` is always `NULL`)
- for functional base-learners like `bsignal(x, s)` it does not contain the evaluation points `s` (could be solved with if statements)

**Comment by davidruegamer** [comment]
Right. Sounds familar. There is a quite fitting label on github for this: *wontfix* :wink:

**Comment by sbrockhaus** [comment]
agreed we keep it as it is. I just added some comments in the code to explain why...
